### ISSUE TITLE
shell variables adding a newline?

### ISSUE THREAD

**Issue by JakobCh** [lunaboards-dev/LuaComp#1]
I seam to have a problem where using $(var) or $[{var}] adds a newline after inserting the variable.

Build script:
`export TESTVAR="Lets go"`
`luacomp test.lua -O out.lua`

Lua file:
`print($(TESTVAR))`

Output:
`print("Lets go`
`")`

**Comment by lunaboards-dev** [comment]
I believe this has been fixed.
