### ISSUE TITLE
[ Enhancement ] If-else directives

### ISSUE THREAD

**Issue by atirutw** [lunaboards-dev/LuaComp#3]
This will make it easier to conditionally include codes in different situations such as including codes for debugging that have to be removed in release builds, etc.

**Comment by lunaboards-dev** [comment]
```lua
@[[if condition then]]
-- code here
@[[else]]
-- other code here
@[[end]]
```

**Comment by atirutw** [comment]
> ```lua
> @[[if condition then]]
> ```

~~Does this work with normal variables or...?~~

NVM I just tested it
